/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq;

import edu.trucktrack.jooq.tables.Employee;
import edu.trucktrack.jooq.tables.EmployeeExpenses;
import edu.trucktrack.jooq.tables.Tag;
import edu.trucktrack.jooq.tables.Truck;
import edu.trucktrack.jooq.tables.WorkTrip;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_EMPLOYEE_EXPENSES_NAME = Internal.createIndex(DSL.name("idx_employee_expenses_name"), EmployeeExpenses.EMPLOYEE_EXPENSES, new OrderField[] { EmployeeExpenses.EMPLOYEE_EXPENSES.NAME }, false);
    public static final Index IDX_EMPLOYEE_EXPENSES_SALARY = Internal.createIndex(DSL.name("idx_employee_expenses_salary"), EmployeeExpenses.EMPLOYEE_EXPENSES, new OrderField[] { EmployeeExpenses.EMPLOYEE_EXPENSES.VALUE }, false);
    public static final Index IDX_EMPLOYEE_NAME = Internal.createIndex(DSL.name("idx_employee_name"), Employee.EMPLOYEE, new OrderField[] { Employee.EMPLOYEE.NAME }, false);
    public static final Index IDX_TAG_NAME = Internal.createIndex(DSL.name("idx_tag_name"), Tag.TAG, new OrderField[] { Tag.TAG.NAME }, false);
    public static final Index IDX_TRUCK_NAME = Internal.createIndex(DSL.name("idx_truck_name"), Truck.TRUCK, new OrderField[] { Truck.TRUCK.NAME }, false);
    public static final Index IDX_TRUCK_VIN_CODE = Internal.createIndex(DSL.name("idx_truck_vin_code"), Truck.TRUCK, new OrderField[] { Truck.TRUCK.VIN_CODE }, true);
    public static final Index IDX_WORK_TRIP_CLOSED_AT = Internal.createIndex(DSL.name("idx_work_trip_closed_at"), WorkTrip.WORK_TRIP, new OrderField[] { WorkTrip.WORK_TRIP.CLOSED_AT }, false);
    public static final Index IDX_WORK_TRIP_NAME = Internal.createIndex(DSL.name("idx_work_trip_name"), WorkTrip.WORK_TRIP, new OrderField[] { WorkTrip.WORK_TRIP.NAME }, false);
    public static final Index IDX_WORK_TRIP_SALARY = Internal.createIndex(DSL.name("idx_work_trip_salary"), WorkTrip.WORK_TRIP, new OrderField[] { WorkTrip.WORK_TRIP.SALARY }, false);
}
