/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq;


import edu.trucktrack.jooq.tables.Company;
import edu.trucktrack.jooq.tables.Currency;
import edu.trucktrack.jooq.tables.Employee;
import edu.trucktrack.jooq.tables.EmployeeExpenses;
import edu.trucktrack.jooq.tables.EmployeeExpensesTag;
import edu.trucktrack.jooq.tables.EmployeeRoles;
import edu.trucktrack.jooq.tables.Roles;
import edu.trucktrack.jooq.tables.SalaryType;
import edu.trucktrack.jooq.tables.Tag;
import edu.trucktrack.jooq.tables.Truck;
import edu.trucktrack.jooq.tables.WorkTrip;
import edu.trucktrack.jooq.tables.WorkTripCargoHistory;
import edu.trucktrack.jooq.tables.WorkTripSalaryHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Company.COMPANY,
                Currency.CURRENCY,
                Employee.EMPLOYEE,
                EmployeeExpenses.EMPLOYEE_EXPENSES,
                EmployeeExpensesTag.EMPLOYEE_EXPENSES_TAG,
                SalaryType.SALARY_TYPE,
                Tag.TAG,
                Truck.TRUCK,
                WorkTrip.WORK_TRIP,
                WorkTripCargoHistory.WORK_TRIP_CARGO_HISTORY,
                WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY,
                EmployeeRoles.EMPLOYEE_ROLES,
                Roles.ROLES
        );
    }
}
