/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq;


import edu.trucktrack.jooq.tables.Company;
import edu.trucktrack.jooq.tables.Currency;
import edu.trucktrack.jooq.tables.Employee;
import edu.trucktrack.jooq.tables.EmployeeExpenses;
import edu.trucktrack.jooq.tables.EmployeeExpensesTag;
import edu.trucktrack.jooq.tables.SalaryType;
import edu.trucktrack.jooq.tables.Tag;
import edu.trucktrack.jooq.tables.Truck;
import edu.trucktrack.jooq.tables.WorkTrip;
import edu.trucktrack.jooq.tables.WorkTripCargoHistory;
import edu.trucktrack.jooq.tables.WorkTripSalaryHistory;

/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.currency</code>.
     */
    public static final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>public.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>public.employee_expenses</code>.
     */
    public static final EmployeeExpenses EMPLOYEE_EXPENSES = EmployeeExpenses.EMPLOYEE_EXPENSES;

    /**
     * The table <code>public.employee_expenses_tag</code>.
     */
    public static final EmployeeExpensesTag EMPLOYEE_EXPENSES_TAG = EmployeeExpensesTag.EMPLOYEE_EXPENSES_TAG;

    /**
     * The table <code>public.salary_type</code>.
     */
    public static final SalaryType SALARY_TYPE = SalaryType.SALARY_TYPE;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>public.truck</code>.
     */
    public static final Truck TRUCK = Truck.TRUCK;

    /**
     * The table <code>public.work_trip</code>.
     */
    public static final WorkTrip WORK_TRIP = WorkTrip.WORK_TRIP;

    /**
     * The table <code>public.work_trip_cargo_history</code>.
     */
    public static final WorkTripCargoHistory WORK_TRIP_CARGO_HISTORY = WorkTripCargoHistory.WORK_TRIP_CARGO_HISTORY;

    /**
     * The table <code>public.work_trip_salary_history</code>.
     */
    public static final WorkTripSalaryHistory WORK_TRIP_SALARY_HISTORY = WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY;
}
