/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.dao.jooq.tables;


import edu.trucktrack.dao.jooq.Public;
import edu.trucktrack.dao.jooq.tables.records.SalaryTypeRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalaryType extends TableImpl<SalaryTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.salary_type</code>
     */
    public static final SalaryType SALARY_TYPE = new SalaryType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SalaryTypeRecord> getRecordType() {
        return SalaryTypeRecord.class;
    }

    /**
     * The column <code>public.salary_type.id</code>.
     */
    public final TableField<SalaryTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.salary_type.name</code>.
     */
    public final TableField<SalaryTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    private SalaryType(Name alias, Table<SalaryTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SalaryType(Name alias, Table<SalaryTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.salary_type</code> table reference
     */
    public SalaryType(String alias) {
        this(DSL.name(alias), SALARY_TYPE);
    }

    /**
     * Create an aliased <code>public.salary_type</code> table reference
     */
    public SalaryType(Name alias) {
        this(alias, SALARY_TYPE);
    }

    /**
     * Create a <code>public.salary_type</code> table reference
     */
    public SalaryType() {
        this(DSL.name("salary_type"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SalaryTypeRecord, Long> getIdentity() {
        return (Identity<SalaryTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SalaryTypeRecord> getPrimaryKey() {
        return Internal.createUniqueKey(SalaryType.SALARY_TYPE, DSL.name("salary_type_pkey"), new TableField[] { SalaryType.SALARY_TYPE.ID }, true);
    }

    @Override
    public SalaryType as(String alias) {
        return new SalaryType(DSL.name(alias), this);
    }

    @Override
    public SalaryType as(Name alias) {
        return new SalaryType(alias, this);
    }

    @Override
    public SalaryType as(Table<?> alias) {
        return new SalaryType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SalaryType rename(String name) {
        return new SalaryType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalaryType rename(Name name) {
        return new SalaryType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SalaryType rename(Table<?> name) {
        return new SalaryType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
