/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables;


import edu.trucktrack.jooq.Public;
import edu.trucktrack.jooq.tables.records.WorkTripRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.Function10;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.OrderField;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WorkTrip extends TableImpl<WorkTripRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.work_trip</code>
     */
    public static final WorkTrip WORK_TRIP = new WorkTrip();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkTripRecord> getRecordType() {
        return WorkTripRecord.class;
    }

    /**
     * The column <code>public.work_trip.id</code>.
     */
    public final TableField<WorkTripRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.work_trip.name</code>.
     */
    public final TableField<WorkTripRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.work_trip.description</code>.
     */
    public final TableField<WorkTripRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.work_trip.employee_id</code>.
     */
    public final TableField<WorkTripRecord, Integer> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.work_trip.truck_id</code>.
     */
    public final TableField<WorkTripRecord, Integer> TRUCK_ID = createField(DSL.name("truck_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.work_trip.salary</code>.
     */
    public final TableField<WorkTripRecord, Integer> SALARY = createField(DSL.name("salary"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.work_trip.currency_id</code>.
     */
    public final TableField<WorkTripRecord, Integer> CURRENCY_ID = createField(DSL.name("currency_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.work_trip.active</code>.
     */
    public final TableField<WorkTripRecord, Boolean> ACTIVE = createField(DSL.name("active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("true", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.work_trip.closed_at</code>.
     */
    public final TableField<WorkTripRecord, LocalDateTime> CLOSED_AT = createField(DSL.name("closed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.work_trip.created_at</code>.
     */
    public final TableField<WorkTripRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.inline("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private WorkTrip(Name alias, Table<WorkTripRecord> aliased) {
        this(alias, aliased, null);
    }

    private WorkTrip(Name alias, Table<WorkTripRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.work_trip</code> table reference
     */
    public WorkTrip(String alias) {
        this(DSL.name(alias), WORK_TRIP);
    }

    /**
     * Create an aliased <code>public.work_trip</code> table reference
     */
    public WorkTrip(Name alias) {
        this(alias, WORK_TRIP);
    }

    /**
     * Create a <code>public.work_trip</code> table reference
     */
    public WorkTrip() {
        this(DSL.name("work_trip"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(
                Internal.createIndex(DSL.name("idx_work_trip_closed_at"), WorkTrip.WORK_TRIP, new OrderField[]{WorkTrip.WORK_TRIP.CLOSED_AT}, false),
                Internal.createIndex(DSL.name("idx_work_trip_name"), WorkTrip.WORK_TRIP, new OrderField[]{WorkTrip.WORK_TRIP.NAME}, false),
                Internal.createIndex(DSL.name("idx_work_trip_salary"), WorkTrip.WORK_TRIP, new OrderField[]{WorkTrip.WORK_TRIP.SALARY}, false)
        );
    }

    @Override
    public Identity<WorkTripRecord, Long> getIdentity() {
        return (Identity<WorkTripRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WorkTripRecord> getPrimaryKey() {
        return Internal.createUniqueKey(WorkTrip.WORK_TRIP, DSL.name("work_trip_pkey"), new TableField[]{WorkTrip.WORK_TRIP.ID}, true);
    }

    @Override
    public WorkTrip as(String alias) {
        return new WorkTrip(DSL.name(alias), this);
    }

    @Override
    public WorkTrip as(Name alias) {
        return new WorkTrip(alias, this);
    }

    @Override
    public WorkTrip as(Table<?> alias) {
        return new WorkTrip(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkTrip rename(String name) {
        return new WorkTrip(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkTrip rename(Name name) {
        return new WorkTrip(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkTrip rename(Table<?> name) {
        return new WorkTrip(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, Integer, Integer, Integer, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Long, ? super String, ? super String, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Long, ? super String, ? super String, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? super Boolean, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
