/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables.record;


import java.time.LocalDateTime;

import edu.trucktrack.jooq.tables.Employee;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record9<Long, Integer, String, String, String, Boolean, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employee.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employee.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.employee.company_id</code>.
     */
    public void setCompanyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employee.company_id</code>.
     */
    public Integer getCompanyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.employee.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employee.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.employee.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.employee.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.employee.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.employee.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.employee.active</code>.
     */
    public void setActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.employee.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.employee.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.employee.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.employee.currency_id</code>.
     */
    public void setCurrencyId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.employee.currency_id</code>.
     */
    public Integer getCurrencyId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.employee.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.employee.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Integer, String, String, String, Boolean, String, Integer, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Integer, String, String, String, Boolean, String, Integer, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Employee.EMPLOYEE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Employee.EMPLOYEE.COMPANY_ID;
    }

    @Override
    public Field<String> field3() {
        return Employee.EMPLOYEE.NAME;
    }

    @Override
    public Field<String> field4() {
        return Employee.EMPLOYEE.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Employee.EMPLOYEE.PASSWORD;
    }

    @Override
    public Field<Boolean> field6() {
        return Employee.EMPLOYEE.ACTIVE;
    }

    @Override
    public Field<String> field7() {
        return Employee.EMPLOYEE.PHONE_NUMBER;
    }

    @Override
    public Field<Integer> field8() {
        return Employee.EMPLOYEE.CURRENCY_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Employee.EMPLOYEE.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCompanyId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public Boolean component6() {
        return getActive();
    }

    @Override
    public String component7() {
        return getPhoneNumber();
    }

    @Override
    public Integer component8() {
        return getCurrencyId();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCompanyId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public Boolean value6() {
        return getActive();
    }

    @Override
    public String value7() {
        return getPhoneNumber();
    }

    @Override
    public Integer value8() {
        return getCurrencyId();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public EmployeeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EmployeeRecord value2(Integer value) {
        setCompanyId(value);
        return this;
    }

    @Override
    public EmployeeRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployeeRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EmployeeRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public EmployeeRecord value6(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public EmployeeRecord value7(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public EmployeeRecord value8(Integer value) {
        setCurrencyId(value);
        return this;
    }

    @Override
    public EmployeeRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EmployeeRecord values(Long value1, Integer value2, String value3, String value4, String value5, Boolean value6, String value7, Integer value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Long id, Integer companyId, String name, String email, String password, Boolean active, String phoneNumber, Integer currencyId, LocalDateTime createdAt) {
        super(Employee.EMPLOYEE);

        setId(id);
        setCompanyId(companyId);
        setName(name);
        setEmail(email);
        setPassword(password);
        setActive(active);
        setPhoneNumber(phoneNumber);
        setCurrencyId(currencyId);
        setCreatedAt(createdAt);
    }
}
