/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.dao.jooq.tables.records;


import edu.trucktrack.dao.jooq.tables.Tag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record5<Long, String, Boolean, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tag.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tag.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tag.is_system</code>.
     */
    public void setIsSystem(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag.is_system</code>.
     */
    public Boolean getIsSystem() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.tag.created_by_employee_id</code>.
     */
    public void setCreatedByEmployeeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tag.created_by_employee_id</code>.
     */
    public Integer getCreatedByEmployeeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tag.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tag.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Boolean, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Boolean, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return Tag.TAG.IS_SYSTEM;
    }

    @Override
    public Field<Integer> field4() {
        return Tag.TAG.CREATED_BY_EMPLOYEE_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Tag.TAG.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Boolean component3() {
        return getIsSystem();
    }

    @Override
    public Integer component4() {
        return getCreatedByEmployeeId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Boolean value3() {
        return getIsSystem();
    }

    @Override
    public Integer value4() {
        return getCreatedByEmployeeId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public TagRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagRecord value3(Boolean value) {
        setIsSystem(value);
        return this;
    }

    @Override
    public TagRecord value4(Integer value) {
        setCreatedByEmployeeId(value);
        return this;
    }

    @Override
    public TagRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TagRecord values(Long value1, String value2, Boolean value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Long id, String name, Boolean isSystem, Integer createdByEmployeeId, LocalDateTime createdAt) {
        super(Tag.TAG);

        setId(id);
        setName(name);
        setIsSystem(isSystem);
        setCreatedByEmployeeId(createdByEmployeeId);
        setCreatedAt(createdAt);
    }
}
