/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables.records;


import edu.trucktrack.jooq.tables.EmployeeRoles;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRolesRecord extends TableRecordImpl<EmployeeRolesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employee_roles.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employee_roles.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employee_roles.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employee_roles.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EmployeeRoles.EMPLOYEE_ROLES.EMPLOYEE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return EmployeeRoles.EMPLOYEE_ROLES.ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getEmployeeId();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public Integer value1() {
        return getEmployeeId();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public EmployeeRolesRecord value1(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public EmployeeRolesRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public EmployeeRolesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRolesRecord
     */
    public EmployeeRolesRecord() {
        super(EmployeeRoles.EMPLOYEE_ROLES);
    }

    /**
     * Create a detached, initialised EmployeeRolesRecord
     */
    public EmployeeRolesRecord(Integer employeeId, Integer roleId) {
        super(EmployeeRoles.EMPLOYEE_ROLES);

        setEmployeeId(employeeId);
        setRoleId(roleId);
    }
}
