/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables.records;


import edu.trucktrack.jooq.tables.SalaryType;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalaryTypeRecord extends UpdatableRecordImpl<SalaryTypeRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.salary_type.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.salary_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.salary_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.salary_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SalaryType.SALARY_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return SalaryType.SALARY_TYPE.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public SalaryTypeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SalaryTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SalaryTypeRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalaryTypeRecord
     */
    public SalaryTypeRecord() {
        super(SalaryType.SALARY_TYPE);
    }

    /**
     * Create a detached, initialised SalaryTypeRecord
     */
    public SalaryTypeRecord(Long id, String name) {
        super(SalaryType.SALARY_TYPE);

        setId(id);
        setName(name);
    }
}
