/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables.records;


import edu.trucktrack.jooq.tables.WorkTrip;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkTripRecord extends UpdatableRecordImpl<WorkTripRecord> implements Record10<Long, String, String, Integer, Integer, Integer, Integer, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.work_trip.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.work_trip.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.work_trip.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.work_trip.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.work_trip.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.work_trip.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.work_trip.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.work_trip.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.work_trip.truck_id</code>.
     */
    public void setTruckId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.work_trip.truck_id</code>.
     */
    public Integer getTruckId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.work_trip.salary</code>.
     */
    public void setSalary(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.work_trip.salary</code>.
     */
    public Integer getSalary() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.work_trip.currency_id</code>.
     */
    public void setCurrencyId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.work_trip.currency_id</code>.
     */
    public Integer getCurrencyId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.work_trip.active</code>.
     */
    public void setActive(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.work_trip.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.work_trip.closed_at</code>.
     */
    public void setClosedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.work_trip.closed_at</code>.
     */
    public LocalDateTime getClosedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.work_trip.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.work_trip.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, Integer, Integer, Integer, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Integer, Integer, Integer, Integer, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkTrip.WORK_TRIP.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkTrip.WORK_TRIP.NAME;
    }

    @Override
    public Field<String> field3() {
        return WorkTrip.WORK_TRIP.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return WorkTrip.WORK_TRIP.EMPLOYEE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return WorkTrip.WORK_TRIP.TRUCK_ID;
    }

    @Override
    public Field<Integer> field6() {
        return WorkTrip.WORK_TRIP.SALARY;
    }

    @Override
    public Field<Integer> field7() {
        return WorkTrip.WORK_TRIP.CURRENCY_ID;
    }

    @Override
    public Field<Boolean> field8() {
        return WorkTrip.WORK_TRIP.ACTIVE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return WorkTrip.WORK_TRIP.CLOSED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return WorkTrip.WORK_TRIP.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getEmployeeId();
    }

    @Override
    public Integer component5() {
        return getTruckId();
    }

    @Override
    public Integer component6() {
        return getSalary();
    }

    @Override
    public Integer component7() {
        return getCurrencyId();
    }

    @Override
    public Boolean component8() {
        return getActive();
    }

    @Override
    public LocalDateTime component9() {
        return getClosedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getEmployeeId();
    }

    @Override
    public Integer value5() {
        return getTruckId();
    }

    @Override
    public Integer value6() {
        return getSalary();
    }

    @Override
    public Integer value7() {
        return getCurrencyId();
    }

    @Override
    public Boolean value8() {
        return getActive();
    }

    @Override
    public LocalDateTime value9() {
        return getClosedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public WorkTripRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkTripRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkTripRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public WorkTripRecord value4(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public WorkTripRecord value5(Integer value) {
        setTruckId(value);
        return this;
    }

    @Override
    public WorkTripRecord value6(Integer value) {
        setSalary(value);
        return this;
    }

    @Override
    public WorkTripRecord value7(Integer value) {
        setCurrencyId(value);
        return this;
    }

    @Override
    public WorkTripRecord value8(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public WorkTripRecord value9(LocalDateTime value) {
        setClosedAt(value);
        return this;
    }

    @Override
    public WorkTripRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public WorkTripRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Boolean value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkTripRecord
     */
    public WorkTripRecord() {
        super(WorkTrip.WORK_TRIP);
    }

    /**
     * Create a detached, initialised WorkTripRecord
     */
    public WorkTripRecord(Long id, String name, String description, Integer employeeId, Integer truckId, Integer salary, Integer currencyId, Boolean active, LocalDateTime closedAt, LocalDateTime createdAt) {
        super(WorkTrip.WORK_TRIP);

        setId(id);
        setName(name);
        setDescription(description);
        setEmployeeId(employeeId);
        setTruckId(truckId);
        setSalary(salary);
        setCurrencyId(currencyId);
        setActive(active);
        setClosedAt(closedAt);
        setCreatedAt(createdAt);
    }
}
