/*
 * This file is generated by jOOQ.
 */
package edu.trucktrack.jooq.tables.records;


import edu.trucktrack.jooq.tables.WorkTripSalaryHistory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkTripSalaryHistoryRecord extends UpdatableRecordImpl<WorkTripSalaryHistoryRecord> implements Record6<Long, Integer, Integer, Float, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.work_trip_salary_history.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.work_trip_salary_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.work_trip_salary_history.trip_id</code>.
     */
    public void setTripId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.work_trip_salary_history.trip_id</code>.
     */
    public Integer getTripId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.work_trip_salary_history.salary_type</code>.
     */
    public void setSalaryType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.work_trip_salary_history.salary_type</code>.
     */
    public Integer getSalaryType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.work_trip_salary_history.salary_rate</code>.
     */
    public void setSalaryRate(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.work_trip_salary_history.salary_rate</code>.
     */
    public Float getSalaryRate() {
        return (Float) get(3);
    }

    /**
     * Setter for
     * <code>public.work_trip_salary_history.calculation_value</code>.
     */
    public void setCalculationValue(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.work_trip_salary_history.calculation_value</code>.
     */
    public Integer getCalculationValue() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.work_trip_salary_history.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.work_trip_salary_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, Integer, Float, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Integer, Integer, Float, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.TRIP_ID;
    }

    @Override
    public Field<Integer> field3() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.SALARY_TYPE;
    }

    @Override
    public Field<Float> field4() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.SALARY_RATE;
    }

    @Override
    public Field<Integer> field5() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.CALCULATION_VALUE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTripId();
    }

    @Override
    public Integer component3() {
        return getSalaryType();
    }

    @Override
    public Float component4() {
        return getSalaryRate();
    }

    @Override
    public Integer component5() {
        return getCalculationValue();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTripId();
    }

    @Override
    public Integer value3() {
        return getSalaryType();
    }

    @Override
    public Float value4() {
        return getSalaryRate();
    }

    @Override
    public Integer value5() {
        return getCalculationValue();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public WorkTripSalaryHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord value2(Integer value) {
        setTripId(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord value3(Integer value) {
        setSalaryType(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord value4(Float value) {
        setSalaryRate(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord value5(Integer value) {
        setCalculationValue(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public WorkTripSalaryHistoryRecord values(Long value1, Integer value2, Integer value3, Float value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkTripSalaryHistoryRecord
     */
    public WorkTripSalaryHistoryRecord() {
        super(WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY);
    }

    /**
     * Create a detached, initialised WorkTripSalaryHistoryRecord
     */
    public WorkTripSalaryHistoryRecord(Long id, Integer tripId, Integer salaryType, Float salaryRate, Integer calculationValue, LocalDateTime createdAt) {
        super(WorkTripSalaryHistory.WORK_TRIP_SALARY_HISTORY);

        setId(id);
        setTripId(tripId);
        setSalaryType(salaryType);
        setSalaryRate(salaryRate);
        setCalculationValue(calculationValue);
        setCreatedAt(createdAt);
    }
}
